[package]
name = "repr-discriminant"
version = "2.0.1"
edition = "2024"
description = "Trait to retrieve the discriminant of an enum variant with a repr(T) at runtime"
authors = ["Richard Neumann <neumann@paulmann.de>"]
license = "MIT"
repository = "https://github.com/PaulmannLighting/repr-discriminant"
documentation = "https://docs.rs/repr-discriminant"
categories = ["rust-patterns"]
keywords = ["enum", "discriminant", "repr", "attribute"]
exclude = [".gitignore"]

[dependencies]
repr-discriminant-derive = { version = "1.1", optional = true }

[features]
derive = ["dep:repr-discriminant-derive"]

[lints]
workspace = true